URL_SEARCH = "http://shou.ydns.eu:81/teachers/search_teacher/"
URL_SEND = "http://localhost:3000/send_forward_msg"
URL_ADD = "http://shou.ydns.eu:81/teachers/add/"

smxy="https://smxy.shou.edu.cn/2052/list.htm"
hxxy="https://hyxy.shou.edu.cn/7373/list.htm"
sthj="https://sthj.shou.edu.cn/8784/list.htm"
spxy="https://spxy.shou.edu.cn/8591/list.htm"
jmxy="https://jmxy.shou.edu.cn/849/list.htm"
gcxy="https://gcxy.shou.edu.cn/szdw/list.htm"
xxxy="https://xxxy.shou.edu.cn/szdw/list.htm"
wyxy="https://wyxy.shou.edu.cn/13396/list.htm"
my="https://my.shou.edu.cn/szdw/list.psp"
tyb="https://tyb.shou.edu.cn/8864/list.htm"
